#!/usr/bin/env bash
# Download the outputs of the chip-size kernels (kaggle/push_sizes.sh) and compare
# the CNN-PPO baseline with the direction-aware GCN on the same held-out jobs of
# each size. push_sizes.sh runs it for each size as soon as both kernels have
# finished; run it by hand from anywhere to redo a size:
#
#   bash kaggle/fetch_sizes.sh
#   SIZES="50 60" bash kaggle/fetch_sizes.sh
#
# Outputs: kaggle/output/chip_size/<N>x<N>-{cnn,dirgcn}/ (kernel log, runs/ and the
# kernel's own evaluation in results/), results/chip_size/<N>x<N>/ (meda
# compare-methods) and results/chip_size/summary.csv (one row per size and method,
# rebuilt from every size compared so far).
set -euo pipefail
cd "$(dirname "$0")/.."
SIZES=${SIZES:-"30 50 60 100 120"}
[[ -x .venv/bin/meda ]] && PATH="$PWD/.venv/bin:$PATH"
# The account the Kaggle CLI is signed in to: ~/.kaggle/access_token (or $KAGGLE_API_TOKEN)
# if present, otherwise kaggle.json.
USER_NAME=${KAGGLE_USERNAME:-$(kaggle config view 2>/dev/null | sed -n 's/^- username: //p')}
if [[ -z "$USER_NAME" ]]; then echo "Set KAGGLE_USERNAME" >&2; exit 1; fi

for N in $SIZES; do
  for m in cnn dirgcn; do
    slug="meda-size-${N}x${N}-$m"
    out="kaggle/output/chip_size/${N}x${N}-$m"
    kaggle kernels status "$USER_NAME/$slug" || true
    mkdir -p "$out"
    kaggle kernels output "$USER_NAME/$slug" -p "$out" || echo "!! could not download $slug" >&2
  done
  cnn="kaggle/output/chip_size/${N}x${N}-cnn/runs/paper_${N}x${N}_healthy"
  dir="kaggle/output/chip_size/${N}x${N}-dirgcn/runs/gnn_dirgcn_${N}x${N}"
  if [[ -d "$cnn" && -d "$dir" ]]; then
    meda compare-methods --method CNN-PPO "$cnn" --method DirGCN-maxpool-PPO "$dir" \
      --episodes 500 --out "results/chip_size/${N}x${N}"
  else
    echo "!! ${N}x${N}: missing run folder(s), skipping the comparison" >&2
  fi
done

python3 - <<'PY'
# results/chip_size/summary.csv: the comparison of every size, plus how many epochs
# each run trained and whether the time limit (schedule.max_hours) stopped it.
import csv, glob, json, os, re
rows = []
for table in sorted(glob.glob("results/chip_size/*x*/tables/main_comparison.csv"),
                    key=lambda p: int(re.search(r"/(\d+)x\d+/", p).group(1))):
    size = table.split("/")[2]
    folder = {"CNN-PPO": f"{size}-cnn", "DirGCN-maxpool-PPO": f"{size}-dirgcn"}
    for row in csv.DictReader(open(table)):
        epochs, planned, stopped = [], [], []
        for s in glob.glob(f"kaggle/output/chip_size/{folder.get(row['method'], '?')}/runs/*/seed_*/summary.json"):
            info = json.load(open(s))
            epochs.append(str(info.get("epochs")))
            stopped.append(str(info.get("stopped_by_time_limit", False)))
            cfg = os.path.join(os.path.dirname(s), "config.yaml")
            m = re.search(r"^schedule:\n(?:  .*\n)*?  epochs: (\d+)", open(cfg).read(), re.M) if os.path.exists(cfg) else None
            planned.append(m.group(1) if m else "?")
        rows.append({"chip": size, **row, "epochs_trained": ";".join(epochs),
                     "epochs_planned": ";".join(planned), "stopped_by_time_limit": ";".join(stopped)})
if rows:
    os.makedirs("results/chip_size", exist_ok=True)
    with open("results/chip_size/summary.csv", "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    print(f"results/chip_size/summary.csv: {len(rows)} rows")

    # The same as a Markdown table for docs/PAPER_NOTES.md (regenerated; do not edit by hand).
    names = {"CNN-PPO": "CNN-PPO", "DirGCN-maxpool-PPO": "Direction-aware GCN + max pooling"}
    def hours(v):
        try:
            return f"{float(v) / 3600:.2f}"
        except ValueError:
            return v
    lines = [
        "# Chip-size study: results so far",
        "",
        "Generated by `kaggle/fetch_sizes.sh` from `results/chip_size/<N>x<N>/tables/main_comparison.csv`",
        "and the runs' `summary.json`; do not edit by hand. Healthy chips, one seed per method, the same",
        "500 held-out evaluation jobs for both methods at each size (evaluation of the final model).",
        "",
        "| Chip | Method | Success (%) | Mean cycles | Invalid actions per decision | Env steps to convergence | Epochs trained / planned | Stopped by time limit | Training time (h) |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append("| " + " | ".join([
            r["chip"], names.get(r["method"], r["method"]), r["success_rate_pct"], r["mean_cycles"],
            r["invalid_action_rate"], r["env_steps_to_convergence"] or "not reached",
            f"{r['epochs_trained']} / {r['epochs_planned']}", r["stopped_by_time_limit"], hours(r["train_time_s"]),
        ]) + " |")
    lines += ["", "Success, cycles and invalid actions: held-out evaluation of the final model on 500 jobs "
              "(`meda compare-methods`, job seed 20000). Convergence: the first of three consecutive "
              "per-epoch training evaluations (500 jobs, seed 10000) at or above 95% success."]
    with open("results/chip_size/summary.md", "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("results/chip_size/summary.md written")
PY
